CREATE DATABASE customer_shopping;
USE customer_shopping;
select * from customer_data limit 10;

--Q1. What is the total revenue generated by male vs. female customers?
select gender,Sum(purchase_amount) as revenue
from customer_data
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_data
where discount_applied = 'Yes' and purchase_amount>=(select AVG(purchase_amount )from customer_data);


--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, avg(review_rating) as avg_rating
from customer_data
group by item_purchased
order by avg_rating desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, avg(purchase_amount) as avg_purchase
from customer_data
group by shipping_type;

--Q5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
avg(purchase_amount) as avg_speed,
sum(purchase_amount) as total_revenue
from customer_data
group by subscription_status;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(sum(case when discount_applied='yes' then 1 else 0 end)*100.0/count(*),2) as discount_pct
from customer_data
group by item_purchased
order by discount_pct desc
limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select case 
when previous_purchases = 0 then 'New'
when previous_purchases between 1 and 5 then 'Returning'
else 'loyal'
end as customer_segment,
count(*) as count
from customer_data
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category?
select category, item_purchased,count(*) as total
from customer_data
group by category,item_purchased
order by category, total desc
limit 3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select case
when previous_purchases > 5 then 'Repeat Buyer'
else 'Non-Repeat' end as buyer_type,
subscription_status,
count(*) as count
from customer_data
group by buyer_type, subscription_status;


--Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;



select*from customer_data;

